// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 Gracker (Chris)

const fs = require('node:fs');
const path = require('node:path');

const {loadCatalog, validateCatalog} = require('./catalog.cjs');

const GENERATED_BANNER = '<!-- Generated by Trace/tools/trace-corpus.cjs. Do not edit by hand. -->';

function relativeCase(repoRoot, entry) {
  const clone = JSON.parse(JSON.stringify(entry));
  clone.case_dir = path.relative(repoRoot, entry.case_dir).split(path.sep).join('/');
  clone.manifest_path = path.relative(repoRoot, entry.manifest_path).split(path.sep).join('/');
  return clone;
}

function androidLabel(entry) {
  const release = entry.android?.release ? `Android ${entry.android.release}` : 'Android unknown';
  const api = entry.android?.api_level ? `API ${entry.android.api_level}` : 'API unknown';
  const range = entry.android?.compatibility;
  if (range?.min_api && range?.max_api && range.min_api !== range.max_api) {
    return `${release} / ${api} (tested API ${range.min_api}-${range.max_api})`;
  }
  return `${release} / ${api}`;
}

function markdownTable(cases, kind, directoryPrefix = '') {
  if (cases.length === 0) return '_No cases yet._';
  const header = kind === 'real'
    ? '| Case | Scene | Android | Publication | Analysis |\n| --- | --- | --- | --- | --- |'
    : '| Case | Scene | Android | Base | Coverage |\n| --- | --- | --- | --- | --- | --- |';
  const rows = cases.map((entry) => {
    const link = `./${directoryPrefix}${entry.id}/`;
    if (kind === 'real') {
      const analysisCount = (entry.analysis?.results?.length ?? 0) + (entry.analysis?.logs?.length ?? 0);
      return `| [${entry.title}](${link}) | ${entry.scene} | ${androidLabel(entry)} | ${entry.source?.publication ?? 'unknown'} | ${analysisCount} file(s) |`;
    }
    const coverageCount = (entry.coverage?.skills?.length ?? 0) + (entry.coverage?.strategies?.length ?? 0);
    return `| [${entry.title}](${link}) | ${entry.scene} | ${androidLabel(entry)} | ${entry.construction?.base_case_id ?? '-'} | ${coverageCount} target(s) |`;
  });
  return [header, ...rows].join('\n');
}

function renderRootReadme(catalog) {
  const real = catalog.cases.filter((entry) => entry.kind === 'real');
  const constructed = catalog.cases.filter((entry) => entry.kind === 'constructed');
  return `${GENERATED_BANNER}
# SmartPerfetto Trace Corpus

This directory is the source-controlled trace test and reference corpus.

- [Real trace cases](./real/README.md): ${real.length}
- [Constructed trace cases](./constructed/README.md): ${constructed.length}
- [Machine-readable catalog](./catalog.json)
- [Skill and Strategy coverage](./coverage.json)

## Real cases

${markdownTable(real, 'real', 'real/')}

## Constructed cases

${markdownTable(constructed, 'constructed', 'constructed/')}
`;
}

function renderKindReadme(catalog, kind) {
  const cases = catalog.cases.filter((entry) => entry.kind === kind);
  const title = kind === 'real' ? 'Real Trace Cases' : 'Constructed Trace Cases';
  const note = kind === 'real'
    ? 'New captures are first imported under ignored `.private/` staging and require explicit review before promotion.'
    : 'Run `npm run trace:build` to materialize base-plus-overlay traces under `Trace/.generated/`.';
  return `${GENERATED_BANNER}
# ${title}

${note}

${markdownTable(cases, kind)}
`;
}

function generatedFiles(repoRoot) {
  const catalog = loadCatalog(repoRoot);
  const validation = validateCatalog(repoRoot);
  const serializableCatalog = {
    schema_version: 1,
    cases: catalog.cases.map((entry) => relativeCase(repoRoot, entry)),
  };
  return new Map([
    [path.join(repoRoot, 'Trace/README.md'), renderRootReadme(catalog)],
    [path.join(repoRoot, 'Trace/real/README.md'), renderKindReadme(catalog, 'real')],
    [path.join(repoRoot, 'Trace/constructed/README.md'), renderKindReadme(catalog, 'constructed')],
    [path.join(repoRoot, 'Trace/catalog.json'), `${JSON.stringify(serializableCatalog, null, 2)}\n`],
    [path.join(repoRoot, 'Trace/coverage.json'), `${JSON.stringify({schema_version: 1, ...validation.coverage}, null, 2)}\n`],
  ]);
}

function writeIndexes(repoRoot, options = {}) {
  const files = generatedFiles(repoRoot);
  const changed = [];
  for (const [filePath, content] of files) {
    const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
    if (current === content) continue;
    if (options.check) {
      throw new Error(`stale generated file: ${path.relative(repoRoot, filePath)}`);
    }
    fs.mkdirSync(path.dirname(filePath), {recursive: true});
    fs.writeFileSync(filePath, content);
    changed.push(path.relative(repoRoot, filePath).split(path.sep).join('/'));
  }
  return {changed};
}

module.exports = {generatedFiles, writeIndexes};
