// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 Gracker (Chris)
// This file is part of SmartPerfetto. See LICENSE for details.

/**
 * Unified Session State Snapshot
 *
 * Single source of truth for persistence, report generation, and session restoration.
 * Replaces the fragile 7-phase persistence cascade (7 sequential read-modify-write
 * cycles on the same SQLite metadata JSON blob) with one atomic write.
 *
 * Written at analysis completion; read by resume, report, and SSE reconnect paths.
 *
 * Key invariants:
 * 1. Snapshot is the single source of truth for report generation — never assemble
 *    from live getters + fallback chains.
 * 2. Snapshot is written atomically — one UPDATE metadata call, not 6+ sequential RMW.
 * 3. All restoration paths read the same snapshot — resume, report, SSE reconnect.
 * 4. ClaudeRuntime Maps = live cache; snapshot = durable copy.
 * 5. Backward compatibility through dual-write — no breaking changes for old sessions.
 */

import type { AnalysisNote, AnalysisPlanV3, Hypothesis, UncertaintyFlag } from './types';
import type { StoredArtifact } from './artifactStore';
import type { ArchitectureInfo } from '../agent/detectors/types';
import type { DataEnvelope } from '../types/dataContract';
import type { ClaimSupportV1 } from '../types/evidenceContract';
import type { ClaimVerificationResult } from '../types/claimVerification';
import type { IdentityResolutionV1 } from '../types/identityContract';
import type { CodeAwareMode } from '../services/codebase/codeAwareFeature';
import type { CodeLookupSummary } from '../services/codebase/codeLookupLedger';
import type { AgentRuntimeKind } from '../services/providerManager/types';
import type {OutputLanguage} from './outputLanguage';

export type ComparisonSourceKind = 'raw_trace_pair' | 'analysis_result_snapshots';

export interface ComparisonReportSection {
  source: ComparisonSourceKind;
  title: string;
  markdown: string;
  html: string;
  limitations?: string[];
  evidencePack?: unknown;
}

// =============================================================================
// Typed sub-interfaces — replace inline anonymous types from AnalysisSession
// =============================================================================

/** A step in the conversation timeline (SSE event log). */
export interface ConversationStep {
  eventId: string;
  ordinal: number;
  phase: 'progress' | 'thinking' | 'tool' | 'result' | 'error';
  role: 'agent' | 'system';
  text: string;
  timestamp: number;
  sourceEventType?: string;
}

/** A query submitted by the user in a specific turn. */
export interface QueryHistoryEntry {
  turn: number;
  query: string;
  timestamp: number;
}

/** A conclusion generated by the agent after a specific turn. */
export interface ConclusionHistoryEntry {
  turn: number;
  conclusion: string;
  confidence: number;
  timestamp: number;
}

/** An inter-agent dialogue entry (task dispatch / response / question). */
export interface AgentDialogueEntry {
  agentId: string;
  type: 'task' | 'response' | 'question';
  content: any;
  timestamp: number;
}

/** A response from a sub-agent task. */
export interface AgentResponseEntry {
  taskId: string;
  agentId: string;
  response: any;
  timestamp: number;
}

export interface SnapshotRunContext {
  runId: string;
  requestId: string;
  sequence: number;
  query: string;
  startedAt: number;
  completedAt?: number;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'quota_exceeded';
  error?: string;
}

export interface SnapshotEngineProviderState {
  /** Provider profile that supplied runtime credentials; null means env/default fallback. */
  providerId?: string | null;
  /** Non-secret provider/runtime snapshot hash for SDK state reuse checks. */
  providerSnapshotHash?: string | null;
}

export type ProviderContinuityBreakReason = 'provider_snapshot_hash_mismatch';

export interface ProviderContinuityBreak {
  at: number;
  previousProviderHash: string;
  reason: ProviderContinuityBreakReason;
}

export type SessionLineageReason = 'cli-level3-degraded';

export interface SessionLineage {
  previousBackendSessionId: string;
  reason: SessionLineageReason;
  at: number;
}

export interface ClaudeSnapshotEngineState {
  sdkSessionId?: string;
  sdkSessionMode?: 'full';
}

export interface OpenAISnapshotEngineState {
  history?: unknown[];
  lastResponseId?: string;
  runState?: string;
}

export type ThirdPartyOpaqueDegradedReason =
  | 'not_json_serializable'
  | 'too_large'
  | 'missing_required_fields'
  | 'state_unavailable'
  | 'session_restore_failed';

export interface PiAgentCoreOpaqueState {
  version: 1;
  messages?: unknown[];
  messageCount: number;
  originalMessageCount?: number;
  truncated?: boolean;
  byteSize?: number;
  degradedReason?: ThirdPartyOpaqueDegradedReason;
}

export interface OpenCodeOpaqueState {
  version: 1;
  openCodeSessionId?: string;
  projectDir?: string;
  homeDir?: string;
  configDir?: string;
  degradedReason?: ThirdPartyOpaqueDegradedReason;
}

export interface PiAgentCoreSnapshotEngineState {
  opaque?: PiAgentCoreOpaqueState;
}

export interface OpenCodeSnapshotEngineState {
  opaque?: OpenCodeOpaqueState;
}

export type SnapshotEngineState =
  | {
      kind: 'claude-agent-sdk';
      provider: SnapshotEngineProviderState;
      claude: ClaudeSnapshotEngineState;
      openai?: never;
      pi?: never;
    }
  | {
      kind: 'openai-agents-sdk';
      provider: SnapshotEngineProviderState;
      openai: OpenAISnapshotEngineState;
      claude?: never;
      pi?: never;
    }
  | {
      kind: 'pi-agent-core';
      provider: SnapshotEngineProviderState;
      pi: PiAgentCoreSnapshotEngineState;
      claude?: never;
      openai?: never;
      opencode?: never;
    }
  | {
      kind: 'opencode';
      provider: SnapshotEngineProviderState;
      opencode: OpenCodeSnapshotEngineState;
      claude?: never;
      openai?: never;
      pi?: never;
    };

interface EngineProviderStateInput {
  providerId?: string | null;
  providerSnapshotHash?: string | null;
}

function createSnapshotEngineProviderState(
  input: EngineProviderStateInput,
): SnapshotEngineProviderState {
  return {
    providerId: input.providerId ?? null,
    providerSnapshotHash: input.providerSnapshotHash ?? null,
  };
}

export function createClaudeSnapshotEngineState(
  input: EngineProviderStateInput & ClaudeSnapshotEngineState,
): SnapshotEngineState {
  return {
    kind: 'claude-agent-sdk',
    provider: createSnapshotEngineProviderState(input),
    claude: {
      sdkSessionId: input.sdkSessionId,
      sdkSessionMode: input.sdkSessionMode,
    },
  };
}

export function createOpenAISnapshotEngineState(
  input: EngineProviderStateInput & OpenAISnapshotEngineState,
): SnapshotEngineState {
  return {
    kind: 'openai-agents-sdk',
    provider: createSnapshotEngineProviderState(input),
    openai: {
      history: input.history,
      lastResponseId: input.lastResponseId,
      runState: input.runState,
    },
  };
}

export function createPiAgentCoreSnapshotEngineState(
  input: EngineProviderStateInput & PiAgentCoreSnapshotEngineState = {},
): SnapshotEngineState {
  return {
    kind: 'pi-agent-core',
    provider: createSnapshotEngineProviderState(input),
    pi: {
      opaque: input.opaque,
    },
  };
}

export function createOpenCodeSnapshotEngineState(
  input: EngineProviderStateInput & OpenCodeSnapshotEngineState = {},
): SnapshotEngineState {
  return {
    kind: 'opencode',
    provider: createSnapshotEngineProviderState(input),
    opencode: {
      opaque: input.opaque,
    },
  };
}

export function getSnapshotRuntimeKind(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'agentRuntimeKind'> | null | undefined,
): AgentRuntimeKind | undefined {
  return snapshot?.engineState?.kind ?? snapshot?.agentRuntimeKind;
}

export function getSnapshotRuntimeProviderId(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'agentRuntimeProviderId'> | null | undefined,
): string | null | undefined {
  const provider = snapshot?.engineState?.provider;
  if (provider && Object.prototype.hasOwnProperty.call(provider, 'providerId')) {
    return provider.providerId ?? null;
  }
  return snapshot?.agentRuntimeProviderId;
}

export function getSnapshotRuntimeProviderSnapshotHash(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'agentRuntimeProviderSnapshotHash'> | null | undefined,
): string | null | undefined {
  const provider = snapshot?.engineState?.provider;
  if (provider && Object.prototype.hasOwnProperty.call(provider, 'providerSnapshotHash')) {
    return provider.providerSnapshotHash ?? null;
  }
  return snapshot?.agentRuntimeProviderSnapshotHash;
}

export function getClaudeSnapshotEngineState(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'sdkSessionId' | 'sdkSessionMode'>,
): ClaudeSnapshotEngineState | undefined {
  if (snapshot.engineState) {
    return snapshot.engineState.kind === 'claude-agent-sdk'
      ? snapshot.engineState.claude
      : undefined;
  }
  if (snapshot.sdkSessionId || snapshot.sdkSessionMode) {
    return {
      sdkSessionId: snapshot.sdkSessionId,
      sdkSessionMode: snapshot.sdkSessionMode,
    };
  }
  return undefined;
}

export function getOpenAISnapshotEngineState(
  snapshot: Pick<SessionStateSnapshot, 'engineState' | 'openAIHistory' | 'openAILastResponseId' | 'openAIRunState' | 'sdkSessionId'>,
): OpenAISnapshotEngineState | undefined {
  if (snapshot.engineState) {
    return snapshot.engineState.kind === 'openai-agents-sdk'
      ? snapshot.engineState.openai
      : undefined;
  }
  if (snapshot.openAIHistory || snapshot.openAILastResponseId || snapshot.openAIRunState || snapshot.sdkSessionId) {
    return {
      history: snapshot.openAIHistory,
      lastResponseId: snapshot.openAILastResponseId || snapshot.sdkSessionId,
      runState: snapshot.openAIRunState,
    };
  }
  return undefined;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

export function getPiAgentCoreSnapshotEngineState(
  snapshot: Pick<SessionStateSnapshot, 'engineState'>,
): PiAgentCoreSnapshotEngineState | undefined {
  if (snapshot.engineState?.kind !== 'pi-agent-core') return undefined;
  const opaque = snapshot.engineState.pi.opaque;
  if (!isRecord(opaque) || opaque.version !== 1) return undefined;
  return {
    opaque: {
      version: 1,
      messages: Array.isArray(opaque.messages) ? opaque.messages : undefined,
      messageCount: typeof opaque.messageCount === 'number' ? opaque.messageCount : 0,
      originalMessageCount: typeof opaque.originalMessageCount === 'number'
        ? opaque.originalMessageCount
        : undefined,
      truncated: typeof opaque.truncated === 'boolean' ? opaque.truncated : undefined,
      byteSize: typeof opaque.byteSize === 'number' ? opaque.byteSize : undefined,
      degradedReason: typeof opaque.degradedReason === 'string'
        ? opaque.degradedReason as ThirdPartyOpaqueDegradedReason
        : undefined,
    },
  };
}

export function getOpenCodeSnapshotEngineState(
  snapshot: Pick<SessionStateSnapshot, 'engineState'>,
): OpenCodeSnapshotEngineState | undefined {
  if (snapshot.engineState?.kind !== 'opencode') return undefined;
  const opaque = snapshot.engineState.opencode.opaque;
  if (!isRecord(opaque) || opaque.version !== 1) return undefined;
  return {
    opaque: {
      version: 1,
      openCodeSessionId: typeof opaque.openCodeSessionId === 'string' ? opaque.openCodeSessionId : undefined,
      projectDir: typeof opaque.projectDir === 'string' ? opaque.projectDir : undefined,
      homeDir: typeof opaque.homeDir === 'string' ? opaque.homeDir : undefined,
      configDir: typeof opaque.configDir === 'string' ? opaque.configDir : undefined,
      degradedReason: typeof opaque.degradedReason === 'string'
        ? opaque.degradedReason as ThirdPartyOpaqueDegradedReason
        : undefined,
    },
  };
}

export function normalizeSessionStateSnapshot(
  snapshot: SessionStateSnapshot,
): SessionStateSnapshot {
  if (snapshot.engineState) return snapshot;

  const runtimeKind =
    snapshot.agentRuntimeKind
    ?? (
      snapshot.openAIHistory || snapshot.openAILastResponseId || snapshot.openAIRunState
        ? 'openai-agents-sdk'
        : undefined
    )
    ?? (
      snapshot.sdkSessionId || snapshot.sdkSessionMode
        ? 'claude-agent-sdk'
        : undefined
    );

  if (runtimeKind === 'claude-agent-sdk') {
    return {
      ...snapshot,
      engineState: createClaudeSnapshotEngineState({
        providerId: snapshot.agentRuntimeProviderId,
        providerSnapshotHash: snapshot.agentRuntimeProviderSnapshotHash,
        sdkSessionId: snapshot.sdkSessionId,
        sdkSessionMode: snapshot.sdkSessionMode,
      }),
    };
  }

  if (runtimeKind === 'openai-agents-sdk') {
    return {
      ...snapshot,
      engineState: createOpenAISnapshotEngineState({
        providerId: snapshot.agentRuntimeProviderId,
        providerSnapshotHash: snapshot.agentRuntimeProviderSnapshotHash,
        history: snapshot.openAIHistory,
        lastResponseId: snapshot.openAILastResponseId || snapshot.sdkSessionId,
        runState: snapshot.openAIRunState,
      }),
    };
  }

  if (runtimeKind === 'pi-agent-core') {
    return {
      ...snapshot,
      engineState: createPiAgentCoreSnapshotEngineState({
        providerId: snapshot.agentRuntimeProviderId,
        providerSnapshotHash: snapshot.agentRuntimeProviderSnapshotHash,
      }),
    };
  }

  if (runtimeKind === 'opencode') {
    return {
      ...snapshot,
      engineState: createOpenCodeSnapshotEngineState({
        providerId: snapshot.agentRuntimeProviderId,
        providerSnapshotHash: snapshot.agentRuntimeProviderSnapshotHash,
      }),
    };
  }

  return snapshot;
}

// =============================================================================
// SessionStateSnapshot — the core snapshot type
// =============================================================================

/**
 * Unified session state snapshot.
 *
 * Captures all session state needed for:
 * - Atomic persistence (single SQLite metadata UPDATE)
 * - HTML/JSON report generation (no live getter fallback chains)
 * - Session restoration on resume (all ClaudeRuntime Maps + session arrays)
 */
export interface SessionStateSnapshot {
  /** Schema version — enables future format migrations. */
  version: 1;
  /** When this snapshot was taken. */
  snapshotTimestamp: number;
  sessionId: string;
  traceId: string;
  /** Presentation language pinned to this session/runtime conversation. */
  outputLanguage?: OutputLanguage;
  /** Reference trace ID for comparison mode — enables session restoration in dual-trace context */
  referenceTraceId?: string;
  /** Source model for comparison mode. Raw dual-trace sessions use raw_trace_pair. */
  comparisonSource?: ComparisonSourceKind;
  /** Shared deterministic comparison section used by CLI and HTML reports. */
  comparisonReportSection?: ComparisonReportSection;

  // --- Timeline & History ---
  conversationSteps: ConversationStep[];
  queryHistory: QueryHistoryEntry[];
  conclusionHistory: ConclusionHistoryEntry[];

  // --- Agent Communication ---
  agentDialogue: AgentDialogueEntry[];
  agentResponses: AgentResponseEntry[];

  // --- Data ---
  dataEnvelopes: DataEnvelope[];
  claimSupport?: ClaimSupportV1[];
  claimVerificationResult?: ClaimVerificationResult;
  identityResolutions?: IdentityResolutionV1[];
  /**
   * Protocol-format hypotheses (from AnalysisResult) for report generation.
   * These use the agentProtocol.Hypothesis shape (id, description, status, confidence).
   */
  hypotheses: any[];

  // --- Claude Runtime State (agentv3-specific) ---
  analysisNotes: AnalysisNote[];
  analysisPlan: AnalysisPlanV3 | null;
  planHistory: AnalysisPlanV3[];
  uncertaintyFlags: UncertaintyFlag[];
  /**
   * agentv3-internal hypotheses (richer than protocol format).
   * Used to restore ClaudeRuntime.sessionHypotheses Map on resume.
   * Contains: id, statement, status, basis, evidence, formedAt, resolvedAt.
   */
  claudeHypotheses?: Hypothesis[];

  // --- Cached Detection ---
  architecture?: ArchitectureInfo;
  /** Canonical engine-local runtime state. Product/report state stays top-level. */
  engineState?: SnapshotEngineState;
  /** Legacy Claude/OpenAI runtime mirror kept during the compatible M7 split. */
  sdkSessionId?: string;
  /** Legacy Claude runtime mirror kept during the compatible M7 split. */
  sdkSessionMode?: 'full';

  // --- Backend Runtime State (legacy mirrors; use helpers above for reads) ---
  /** Runtime that produced the snapshot. Omitted for legacy Claude-only snapshots. */
  agentRuntimeKind?: AgentRuntimeKind;
  /**
   * Provider profile that supplied runtime credentials.
   * null means the session is pinned to env/default fallback and must not read
   * the current active Provider Manager profile during restoration.
   */
  agentRuntimeProviderId?: string | null;
  /**
   * Non-secret hash of the provider/runtime configuration that created the SDK
   * session. Resume may only reuse sdkSessionId when this still matches the
   * current resolved provider snapshot.
   */
  agentRuntimeProviderSnapshotHash?: string | null;
  /** Append-only provider/runtime continuity breaks that forced fresh SDK context. */
  continuityBreaks?: ProviderContinuityBreak[];
  /** Authorization partition for source/RAG continuation. */
  analysisContextFingerprint?: string;
  /** Immutable public Knowledge Pack identity pinned to this analysis session. */
  androidInternalsPackPin?: import('../services/androidInternalsPack/types').AndroidInternalsPackIdentity;
  /** Public background citations, kept separate from current-trace evidence. */
  backgroundKnowledgeReferences?: import('../types/sparkContracts').BackgroundKnowledgeReference[];
  /** Backend-session ancestry when a user-visible session had to bridge to a fresh backend session. */
  lineage?: SessionLineage;
  /** OpenAI Agents SDK history for cross-restart multi-turn continuation. */
  openAIHistory?: unknown[];
  /** Last provider response ID from the OpenAI Agents SDK run. */
  openAILastResponseId?: string;
  /** Reserved serialized OpenAI run state for future SDK-native restoration. */
  openAIRunState?: string;
  /** Code-aware analysis mode persisted with the session. */
  codeAwareMode?: CodeAwareMode;
  /** Explicit codebase allowlist used by this session. */
  codebaseIds?: string[];
  /** Non-secret consent/index-generation state captured for resume/report safety. */
  codebaseSnapshot?: Array<{
    codebaseId: string;
    indexGeneration: number;
    activeGeneration?: string;
    contentFingerprint?: string;
    indexedRevision?: string;
    indexedDirty?: boolean;
    commitProvenance?: 'clean_git_revision' | 'dirty_git_worktree' | 'content_only';
    consentHash?: string;
  }>;
  /** Explicit external knowledge allowlist and active provenance for this session. */
  knowledgeSourceIds?: string[];
  knowledgeSourceSnapshot?: Array<{
    sourceId: string;
    indexGeneration: number;
    activeGeneration?: string;
    contentFingerprint: string;
    revision: string;
  }>;
  /** Append-only lookup ledger summary for this session. */
  codeLookupSummary?: CodeLookupSummary;

  // --- Artifact Store (optional, can be large) ---
  artifacts?: StoredArtifact[];

  // --- Run Tracking ---
  runSequence: number;
  conversationOrdinal: number;
  activeRun?: SnapshotRunContext;
  lastRun?: SnapshotRunContext;
}

// =============================================================================
// SessionFieldsForSnapshot — what the route layer provides to takeSnapshot()
// =============================================================================

/**
 * Session-level fields provided by the route layer to `takeSnapshot()`.
 *
 * ClaudeRuntime reads its own Maps (notes, plans, flags, artifacts, architecture,
 * sdkSessionId) internally. The route layer provides the session-scoped arrays
 * that live in the AnalysisSession object.
 */
export interface SessionFieldsForSnapshot {
  /** Presentation language pinned to this session/runtime conversation. */
  outputLanguage?: OutputLanguage;
  /** Reference trace ID for comparison mode session identity. */
  referenceTraceId?: string;
  /** Source model for comparison mode. */
  comparisonSource?: ComparisonSourceKind;
  /** Shared deterministic comparison report section, when available. */
  comparisonReportSection?: ComparisonReportSection;
  conversationSteps: ConversationStep[];
  queryHistory: QueryHistoryEntry[];
  conclusionHistory: ConclusionHistoryEntry[];
  agentDialogue: AgentDialogueEntry[];
  agentResponses: AgentResponseEntry[];
  dataEnvelopes: DataEnvelope[];
  claimSupport?: ClaimSupportV1[];
  claimVerificationResult?: ClaimVerificationResult;
  identityResolutions?: IdentityResolutionV1[];
  /** Protocol-format hypotheses from AnalysisResult. */
  hypotheses: any[];
  /** Provider profile that supplied runtime credentials for this turn; null means env/default fallback. */
  agentRuntimeProviderId?: string | null;
  /** Non-secret hash of the resolved provider/runtime configuration. */
  agentRuntimeProviderSnapshotHash?: string | null;
  /** Append-only provider/runtime continuity breaks that forced fresh SDK context. */
  continuityBreaks?: ProviderContinuityBreak[];
  analysisContextFingerprint?: string;
  androidInternalsPackPin?: SessionStateSnapshot['androidInternalsPackPin'];
  backgroundKnowledgeReferences?: SessionStateSnapshot['backgroundKnowledgeReferences'];
  /** Backend-session ancestry when a user-visible session had to bridge to a fresh backend session. */
  lineage?: SessionLineage;
  codeAwareMode?: CodeAwareMode;
  codebaseIds?: string[];
  codebaseSnapshot?: SessionStateSnapshot['codebaseSnapshot'];
  knowledgeSourceIds?: string[];
  knowledgeSourceSnapshot?: SessionStateSnapshot['knowledgeSourceSnapshot'];
  codeLookupSummary?: CodeLookupSummary;
  runSequence: number;
  conversationOrdinal: number;
  activeRun?: SnapshotRunContext;
  lastRun?: SnapshotRunContext;
}

/** Third-party opaque transcripts are not durable for private source sessions. */
export function sessionFieldsUsePrivateKnowledge(fields: SessionFieldsForSnapshot): boolean {
  return Boolean(
    (fields.codeAwareMode && fields.codeAwareMode !== 'off' && fields.codebaseIds?.length) ||
    fields.knowledgeSourceIds?.length,
  );
}

/**
 * Private retrieval sessions persist only the verified product result and
 * deterministic trace evidence. Intermediate model-authored state must not be
 * replayable after a restart, regardless of the provider runtime in use.
 */
export function projectSessionFieldsForDurableSnapshot(
  fields: SessionFieldsForSnapshot,
): SessionFieldsForSnapshot {
  if (!sessionFieldsUsePrivateKnowledge(fields)) return fields;
  return {
    ...fields,
    comparisonReportSection: undefined,
    conversationSteps: [],
    agentDialogue: [],
    agentResponses: [],
    hypotheses: [],
  };
}
